### ISSUE TITLE
parse service line errors

### ISSUE THREAD

**Issue by seanchann** [coreos/protodoc#8]
hi:
   in my  `*.proto` file,  the code snippet defined below

  ```
  // first request.
  rpc HalfDuplexCall(CreatePjsipEndpointRequest)
    returns (CreatePjsipEndpointResponse);
  ```

 if call `protodoc --directory=./ --parse="service,message" --languages="Go,C++,Java,Python" --title=testdata --output=sample.md` to generate doc, it will be crash.

 ```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/coreos/protodoc/parse.ReadFile(0xc420014860, 0xb, 0xc42004fa38, 0x6, 0xc42001a930)
        /home/seanchann/source/golang/src/github.com/coreos/protodoc/parse/parse.go:233 +0x1293
github.com/coreos/protodoc/parse.ReadDir(0x7ffecb1711ab, 0x2, 0x0, 0x0, 0x6, 0x0, 0x660420)
        /home/seanchann/source/golang/src/github.com/coreos/protodoc/parse/parse.go:82 +0x1a0
main.CommandFunc(0x65dbc0, 0xc420016230, 0x0, 0x5, 0x0, 0x0)
        /home/seanchann/source/golang/src/github.com/coreos/protodoc/main.go:124 +0x7e3
github.com/spf13/cobra.(*Command).execute(0x65dbc0, 0xc4200101f0, 0x5, 0x5, 0x65dbc0, 0xc4200101f0)
        /home/seanchann/source/golang/src/github.com/spf13/cobra/command.go:650 +0x457
github.com/spf13/cobra.(*Command).ExecuteC(0x65dbc0, 0xc4200101d8, 0x0, 0x0)
        /home/seanchann/source/golang/src/github.com/spf13/cobra/command.go:729 +0x339
github.com/spf13/cobra.(*Command).Execute(0x65dbc0, 0x14, 0x48)
        /home/seanchann/source/golang/src/github.com/spf13/cobra/command.go:688 +0x2b
main.main()
        /home/seanchann/source/golang/src/github.com/coreos/protodoc/main.go:173 +0x31
 ```

 it seem not support multiple line define for a rpc api?

**Comment by heyitsanthony** [comment]
The parser isn't very good; it should use something like github.com/dsymonds/gotoc instead of the hack that's there now.

**Comment by seanchann** [comment]
@heyitsanthony  I need to  generate api doc . eg. a markdown file.

**Comment by gyuho** [comment]
@seanchann Yeah, the parser here was created for quick hacks, before https://github.com/dsymonds/gotoc.

We don't have bandwidth right now, but I created an issue to track it https://github.com/coreos/protodoc/issues/9

**Comment by seanchann** [comment]
@heyitsanthony @gyuho  thanks.  I will temporarily modify the file format to circumvent this problem
